image: nfcore/gitpod:latest
tasks:
  - name: Update Nextflow
    command: |
      nextflow self-update
  - name: unset JAVA_TOOL_OPTIONS
    command: |
      unset JAVA_TOOL_OPTIONS

vscode:
  extensions:
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
