image: gitpod/workspace-full-vnc:2024-05-27-17-11-15
tasks:
  - name: Install Nextflow
    init: |
      curl -s https://get.nextflow.io | bash \
      && chmod +x nextflow \
      && mkdir -p .local/bin
      && mv nextflow .local/bin \
      && exit
  #- name: Start web server
  #  init: python -m http.server 8000

ports:
  - port: 5900
    onOpen: open-browser

vscode:
  extensions:
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
