image: gitpod/workspace-full-vnc:2024-05-27-17-11-15
tasks:
  - name: Install Nextflow
    init: |
      curl -s https://get.nextflow.io | bash \
      && chmod +x nextflow \
      && mkdir -p ~/.local/bin \
      && mv nextflow ~/.local/bin \
      && exit
  - name: Install QuPath
    init: |
      cd ~
      curl -OJL https://github.com/qupath/qupath/releases/download/v0.5.1/QuPath-v0.5.1-Linux.tar.xz \
      && tar xf QuPath-v0.5.1-Linux.tar.xz \
      && rm Path-v0.5.1-Linux.tar.xz \
      && ln -s ~/.local/bin ~/QuPath-v0.5.1-Linux/QuPath/bin/QuPath
  - name: Web server
    command: python -m http.server 8000
  - name: Terminal
    command: clear; bash

ports:
  - port: 6080
    onOpen: open-browser
  - port: 8000
    onOpen: open-preview
