image: nfcore/gitpod:latest
tasks:
  - name: Update Nextflow
    init: nextflow self-update
  - name: unset JAVA_TOOL_OPTIONS
    init: unset JAVA_TOOL_OPTIONS
  - name: Start web server
    init: python -m http.server 8000

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
