image: gitpod/workspace-full-vnc:2024-05-27-17-11-15
tasks:
  - name: Install Nextflow
    init: |
      curl -s https://get.nextflow.io | bash \
      && chmod +x nextflow \
      && mkdir -p ~/.local/bin \
      && mv nextflow ~/.local/bin \
      && exit
  - name: Web server
    command: python -m http.server 8000
  - name: Terminal
    command: clear; bash

ports:
  - port: 6080
    onOpen: open-browser
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
